sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t docker4edu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker4edu/docker-react npm run test -- --coverage