sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -e CI=true -t docker4edu/docker-react -f Dockerfil.dev .

script:
  - docker run docker4edu/docker-react npm run test -- --coverage